# Generated by Django 6.0.3 on 2026-04-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за штуку')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Стоимость')),
                ('arrival_date', models.DateField(verbose_name='Дата завоза')),
            ],
            options={
                'verbose_name': 'Остаток товара',
                'verbose_name_plural': 'Остатки товаров',
                'ordering': ['-arrival_date', 'product_name'],
            },
        ),
    ]
