# Generated by Django 6.0.3 on 2026-04-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('code', models.CharField(max_length=30, verbose_name='Код')),
                ('inn', models.CharField(max_length=20, verbose_name='ИНН')),
                ('marked_for_deletion', models.BooleanField(default=False, verbose_name='Помечен на удаление')),
            ],
            options={
                'unique_together': {('code', 'inn')},
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('internal_code', models.CharField(blank=True, max_length=50, verbose_name='Код внутреннего учета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('storage_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='core.department', verbose_name='Место хранения (подразделение)')),
            ],
        ),
    ]
