# Generated by Django 6.0.2 on 2026-03-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(),
        ),
    ]
